import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { FileText, Search, Plus, X, Upload, Sparkles, Download } from 'lucide-react';
import toast from 'react-hot-toast';
import api from '../services/api';

function downloadRecord(r) {
  const dateStr = r.record_date
    ? new Date(r.record_date + 'T00:00:00').toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })
    : '—';
  const dataFields = r.data
    ? Object.entries(r.data)
        .filter(([k]) => k !== 'attachments')
        .map(([k, v]) => `  ${k}: ${typeof v === 'object' ? JSON.stringify(v) : v}`)
        .join('\n')
    : '';
  const attachments = r.data?.attachments?.length
    ? r.data.attachments.map(a => `  • ${a.name}  (${a.size})${a.note ? ' — ' + a.note : ''}`).join('\n')
    : '  None';
  const tags = r.tags?.length ? r.tags.join(', ') : '—';

  const content = `
╔══════════════════════════════════════════════════════════════╗
║              HEALTHSECURE — HEALTH RECORD EXPORT             ║
╚══════════════════════════════════════════════════════════════╝

Record Type   : ${r.record_type}
Title         : ${r.title}
Date          : ${dateStr}
Facility      : ${r.vendor_name || 'Self-uploaded'}
Sensitive     : ${r.is_sensitive ? 'Yes' : 'No'}
Tags          : ${tags}

DESCRIPTION
─────────────────────────────────────────────────────────────
${r.description || '—'}

RECORD DATA
─────────────────────────────────────────────────────────────
${dataFields || '  (no structured data)'}

ATTACHMENTS
─────────────────────────────────────────────────────────────
${attachments}

──────────────────────────────────────────────────────────────
Generated by HealthSecure Platform  |  ${new Date().toLocaleString('en-IN')}
This document is encrypted at rest. Export is for authorised use only.
`.trimStart();

  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = r.data?.attachments?.[0]?.name
    ? r.data.attachments[0].name.replace(/\.[^.]+$/, '.txt')
    : `${r.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_${r.record_date || 'record'}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

const RECORD_TYPES = ['ALL', 'PRESCRIPTION', 'LAB_REPORT', 'DISCHARGE_SUMMARY', 'IMAGING', 'VACCINATION', 'INSURANCE', 'CONSULTATION'];
const RECORD_CATEGORIES = ['CLINICAL', 'DIAGNOSTIC', 'ADMINISTRATIVE', 'FINANCIAL'];

const TYPE_COLORS = {
  PRESCRIPTION: 'bg-blue-100 text-blue-700',
  LAB_REPORT: 'bg-purple-100 text-purple-700',
  DISCHARGE_SUMMARY: 'bg-orange-100 text-orange-700',
  IMAGING: 'bg-green-100 text-green-700',
  VACCINATION: 'bg-teal-100 text-teal-700',
  INSURANCE: 'bg-yellow-100 text-yellow-700',
  CONSULTATION: 'bg-pink-100 text-pink-700',
};

const DEFAULT_FORM = {
  recordType: 'PRESCRIPTION',
  recordCategory: 'CLINICAL',
  title: '',
  description: '',
  recordDate: new Date().toISOString().split('T')[0],
  tags: '',
  isSensitive: false,
  notes: '',
};

function UploadModal({ onClose, onSuccess }) {
  const [form, setForm] = useState(DEFAULT_FORM);
  const [error, setError] = useState('');

  const mutation = useMutation({
    mutationFn: (payload) => api.post('/records/upload', payload).then(r => r.data),
    onSuccess: (data) => { onSuccess(data); onClose(); },
    onError: (err) => setError(err.response?.data?.error || 'Upload failed'),
  });

  const set = (k, v) => setForm(f => ({ ...f, [k]: v }));

  const handleSubmit = (e) => {
    e.preventDefault();
    setError('');
    const payload = {
      recordType: form.recordType,
      recordCategory: form.recordCategory,
      title: form.title,
      description: form.description,
      recordDate: form.recordDate,
      tags: form.tags ? form.tags.split(',').map(t => t.trim()).filter(Boolean) : [],
      isSensitive: form.isSensitive,
      data: { notes: form.notes || form.description, source: 'Patient Self-Upload' },
    };
    mutation.mutate(payload);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm p-4">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg max-h-[90vh] overflow-y-auto">
        <div className="flex items-center justify-between p-5 border-b border-slate-100">
          <div className="flex items-center gap-2">
            <Upload className="w-5 h-5 text-blue-600" />
            <h2 className="text-lg font-bold text-slate-800">Upload Health Record</h2>
          </div>
          <button onClick={onClose} className="p-1.5 rounded-lg hover:bg-slate-100 text-slate-400"><X className="w-4 h-4" /></button>
        </div>

        <form onSubmit={handleSubmit} className="p-5 space-y-4">
          {error && <div className="bg-red-50 border border-red-200 text-red-700 text-sm px-4 py-2 rounded-lg">{error}</div>}

          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block text-xs font-medium text-slate-600 mb-1">Record Type *</label>
              <select value={form.recordType} onChange={e => set('recordType', e.target.value)} className="input-field text-sm" required>
                {RECORD_TYPES.filter(t => t !== 'ALL').map(t => <option key={t}>{t}</option>)}
              </select>
            </div>
            <div>
              <label className="block text-xs font-medium text-slate-600 mb-1">Category</label>
              <select value={form.recordCategory} onChange={e => set('recordCategory', e.target.value)} className="input-field text-sm">
                {RECORD_CATEGORIES.map(c => <option key={c}>{c}</option>)}
              </select>
            </div>
          </div>

          <div>
            <label className="block text-xs font-medium text-slate-600 mb-1">Title *</label>
            <input type="text" value={form.title} onChange={e => set('title', e.target.value)}
              placeholder="e.g. Blood Test Report — June 2026" className="input-field text-sm" required />
          </div>

          <div>
            <label className="block text-xs font-medium text-slate-600 mb-1">Date *</label>
            <input type="date" value={form.recordDate} onChange={e => set('recordDate', e.target.value)} className="input-field text-sm" required />
          </div>

          <div>
            <label className="block text-xs font-medium text-slate-600 mb-1">Description</label>
            <textarea value={form.description} onChange={e => set('description', e.target.value)}
              placeholder="Brief description of the record..." rows={2} className="input-field text-sm resize-none" />
          </div>

          <div>
            <label className="block text-xs font-medium text-slate-600 mb-1">Additional Notes / Data</label>
            <textarea value={form.notes} onChange={e => set('notes', e.target.value)}
              placeholder="Doctor instructions, test values, observations..." rows={3} className="input-field text-sm resize-none" />
          </div>

          <div>
            <label className="block text-xs font-medium text-slate-600 mb-1">Tags (comma-separated)</label>
            <input type="text" value={form.tags} onChange={e => set('tags', e.target.value)}
              placeholder="e.g. annual, blood-test, cardiology" className="input-field text-sm" />
          </div>

          <label className="flex items-center gap-2 cursor-pointer select-none">
            <input type="checkbox" checked={form.isSensitive} onChange={e => set('isSensitive', e.target.checked)}
              className="w-4 h-4 rounded border-slate-300 text-blue-600" />
            <span className="text-sm text-slate-600">Mark as sensitive (requires explicit consent)</span>
          </label>

          <div className="flex gap-3 pt-2">
            <button type="button" onClick={onClose} className="flex-1 py-2.5 rounded-xl border border-slate-200 text-slate-600 text-sm font-medium hover:bg-slate-50">
              Cancel
            </button>
            <button type="submit" disabled={mutation.isPending}
              className="flex-1 py-2.5 rounded-xl bg-blue-600 text-white text-sm font-semibold hover:bg-blue-700 disabled:opacity-60 flex items-center justify-center gap-2">
              {mutation.isPending ? 'Uploading...' : <><Upload className="w-4 h-4" /> Upload Record</>}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

export default function RecordsPage() {
  const [filter, setFilter] = useState('ALL');
  const [search, setSearch] = useState('');
  const [showUpload, setShowUpload] = useState(false);
  const [successMsg, setSuccessMsg] = useState('');
  const queryClient = useQueryClient();

  const { data, isLoading } = useQuery({
    queryKey: ['my-records', filter],
    queryFn: () => api.get(`/records/my${filter !== 'ALL' ? `?recordType=${filter}` : ''}`).then(r => r.data.records),
  });

  const filtered = data?.filter(r => !search || r.title.toLowerCase().includes(search.toLowerCase())) || [];

  const seedMutation = useMutation({
    mutationFn: () => api.post('/records/seed-samples').then(r => r.data),
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['my-records'] });
      toast.success(`${data.seeded} sample records loaded! Total: ${data.total}`);
    },
    onError: (err) => toast.error(err.response?.data?.error || 'Failed to load samples'),
  });

  const handleUploadSuccess = () => {
    queryClient.invalidateQueries({ queryKey: ['my-records'] });
    setSuccessMsg('Record uploaded successfully!');
    setTimeout(() => setSuccessMsg(''), 4000);
  };

  return (
    <div className="space-y-6">
      {showUpload && <UploadModal onClose={() => setShowUpload(false)} onSuccess={handleUploadSuccess} />}

      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-800">Health Records</h1>
          <p className="text-slate-500 text-sm mt-1">All your medical records, encrypted and integrity-verified.</p>
        </div>
        <div className="flex items-center gap-2">
          {data?.length === 0 && (
            <button
              onClick={() => seedMutation.mutate()}
              disabled={seedMutation.isPending}
              className="flex items-center gap-2 px-4 py-2.5 bg-violet-600 text-white rounded-xl text-sm font-semibold hover:bg-violet-700 transition-colors shadow-sm disabled:opacity-60">
              <Sparkles className="w-4 h-4" />
              {seedMutation.isPending ? 'Loading...' : 'Load Sample Records'}
            </button>
          )}
          <button onClick={() => setShowUpload(true)}
            className="flex items-center gap-2 px-4 py-2.5 bg-blue-600 text-white rounded-xl text-sm font-semibold hover:bg-blue-700 transition-colors shadow-sm">
            <Plus className="w-4 h-4" />
            Upload Record
          </button>
        </div>
      </div>

      {successMsg && (
        <div className="bg-green-50 border border-green-200 text-green-700 px-4 py-2.5 rounded-xl text-sm flex items-center gap-2">
          <span>✓</span> {successMsg}
        </div>
      )}

      {/* Filters */}
      <div className="flex flex-col sm:flex-row gap-3">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
          <input type="text" value={search} onChange={e => setSearch(e.target.value)}
            placeholder="Search records..." className="input-field pl-9" />
        </div>
        <div className="flex gap-2 overflow-x-auto pb-1">
          {RECORD_TYPES.map(t => (
            <button key={t} onClick={() => setFilter(t)}
              className={`px-3 py-1.5 rounded-lg text-xs font-medium whitespace-nowrap transition-colors ${
                filter === t ? 'bg-blue-600 text-white' : 'bg-white border border-slate-200 text-slate-600 hover:bg-slate-50'
              }`}>
              {t}
            </button>
          ))}
        </div>
      </div>

      {/* Records */}
      {isLoading && <p className="text-slate-400">Loading records...</p>}
      {filtered.length === 0 && !isLoading && (
        <div className="text-center py-12">
          <FileText className="w-10 h-10 text-slate-300 mx-auto mb-3" />
          <p className="text-slate-500 mb-4">No records found</p>
          <div className="flex items-center justify-center gap-3">
            <button onClick={() => seedMutation.mutate()} disabled={seedMutation.isPending}
              className="inline-flex items-center gap-2 px-4 py-2 bg-violet-600 text-white rounded-lg text-sm font-medium hover:bg-violet-700 disabled:opacity-60">
              <Sparkles className="w-4 h-4" /> {seedMutation.isPending ? 'Loading...' : 'Load Sample Records'}
            </button>
            <button onClick={() => setShowUpload(true)}
              className="inline-flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700">
              <Plus className="w-4 h-4" /> Upload your first record
            </button>
          </div>
        </div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {filtered.map((r) => (
          <div key={r.id} className="card hover:shadow-md transition-shadow">
            <div className="flex items-start justify-between gap-2">
              <div className="flex items-start gap-2 flex-wrap">
                <div className={`px-2 py-0.5 rounded text-xs font-bold ${TYPE_COLORS[r.record_type] || 'bg-slate-100 text-slate-600'}`}>
                  {r.record_type}
                </div>
                {r.is_sensitive && <span className="badge-danger text-xs">Sensitive</span>}
              </div>
              <button
                onClick={() => { downloadRecord(r); toast.success('Download started'); }}
                title="Download record"
                className="flex-shrink-0 flex items-center gap-1 px-2.5 py-1 rounded-lg border border-slate-200 text-slate-500 hover:bg-slate-50 hover:border-blue-300 hover:text-blue-600 text-xs font-medium transition-colors">
                <Download className="w-3.5 h-3.5" /> Download
              </button>
            </div>
            <h3 className="font-semibold text-slate-800 mt-2">{r.title}</h3>
            {r.description && <p className="text-sm text-slate-500 mt-1 line-clamp-2">{r.description}</p>}
            <div className="flex items-center justify-between mt-3 pt-3 border-t border-slate-100">
              <div>
                <p className="text-xs text-slate-400">{r.vendor_name}</p>
              </div>
              <p className="text-xs text-slate-500">{r.record_date ? new Date(r.record_date + 'T00:00:00').toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }) : '—'}</p>
            </div>
            {r.tags?.length > 0 && (
              <div className="flex flex-wrap gap-1 mt-2">
                {r.tags.map(t => <span key={t} className="text-xs bg-slate-100 text-slate-500 px-2 py-0.5 rounded-full">{t}</span>)}
              </div>
            )}
            {r.data?.attachments?.length > 0 && (
              <div className="mt-2 pt-2 border-t border-slate-100">
                <p className="text-xs font-medium text-slate-500 mb-1">📎 Attachments</p>
                {r.data.attachments.map((a, i) => (
                  <div key={i} className="flex items-center gap-2 text-xs text-slate-500">
                    <span>📄</span>
                    <span className="font-medium text-slate-700">{a.name}</span>
                    <span className="text-slate-400">{a.size}</span>
                  </div>
                ))}
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
